export default [
  "strapi::logger",
  "strapi::errors",
  "strapi::security",
  {
    name: "strapi::cors",
    config: {
      origin: [
        "https://personal-web-deploy.vercel.app",
        "http://127.0.0.1:5500",
        "http://localhost:5500",
        "http://localhost:3000",
        "https://shainwaiyan.com",
        "http://shainwaiyan.com",
        "https://www.shainwaiyan.com",
        "http://www.shainwaiyan.com",
        "https://api.shainwaiyan.com",
        "http://api.shainwaiyan.com",
        // ADD THIS LINE - your worker domain
        "https://crawler-detector-and-ssr-ssg-functioner.shainwaiyan2002.workers.dev",
      ],
      headers: [
        "Content-Type",
        "Authorization",
        "Origin",
        "Accept",
        "cache-control",
        "Cache-Control",
        "Pragma",
        "Expires",
        "If-Modified-Since",
        "If-None-Match",
        "ETag",
        "Last-Modified",
        "Content-Length",
        "Content-Range",
        "Range",
      ],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"],
      credentials: true,
      maxAge: 86400,
      preflightContinue: false,
    },
  },
  "strapi::poweredBy",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  {
    name: "global::read-only",
    config: {},
  },
];
